services:
  web:
    image: nginx
    hostname: web
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl

  database:
    image: postgres:16
    hostname: database
    container_name: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./backend/libs/common/src/database/.env.local
    volumes:
      - pgdata:/var/lib/postgresql/data

  products:
    build:
      context: ./backend
      dockerfile: ./apps/products/Dockerfile
      target: runner
    hostname: products
    container_name: products_service
    env_file:
      - ./backend/apps/products/.env.production.local
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    hostname: frontend
    container_name: frontend
    env_file:
      - ./frontend/.env.production.local
    depends_on:
      - products

volumes:
  pgdata:
